#!/usr/bin/env bash
set -e
if [[ "$1" = "purge" ]]; then
  rm -f /etc/profile.d/zz-podman.sh
  rm -f /etc/ld.so.conf.d/podman.conf
  rm -f /etc/systemd/system/podman.service /etc/systemd/system/podman.socket
  systemctl daemon-reload || true
  ldconfig || true
fi
exit 0
